/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
        colors: {
            "deep-slate": "#272c33",
            "tertiary": "#00dbe9",
            "on-tertiary": "#00363a",
            "surface-container-highest": "#343538",
            "error": "#ffb4ab",
            "surface-tint": "#ffb2b8",
            "secondary-fixed-dim": "#b6d300",
            "on-primary-fixed-variant": "#91002c",
            "surface-container-low": "#1a1b1e",
            "on-secondary": "#2c3400",
            "surface-dim": "#121316",
            "on-tertiary-fixed-variant": "#004f54",
            "silver-mist": "#9ea0a9",
            "on-secondary-fixed": "#181e00",
            "surface-container-high": "#292a2d",
            "pitch-black": "#000000",
            "surface": "#121316",
            "primary-container": "#e32652",
            "on-tertiary-fixed": "#002022",
            "inverse-surface": "#e3e2e6",
            "on-tertiary-container": "#000607",
            "background": "#121316",
            "secondary-container": "#d0f100",
            "on-error": "#690005",
            "on-secondary-fixed-variant": "#404c00",
            "inverse-primary": "#be003d",
            "secondary": "#ffffff",
            "on-primary-container": "#ffffff",
            "on-background": "#e3e2e6",
            "primary-fixed": "#ffdadb",
            "outline-variant": "#5b3f41",
            "on-surface": "#e3e2e6",
            "primary-fixed-dim": "#ffb2b8",
            "secondary-fixed": "#d0f100",
            "surface-bright": "#38393c",
            "on-secondary-container": "#5c6b00",
            "on-primary-fixed": "#40000f",
            "on-error-container": "#ffdad6",
            "tertiary-fixed": "#7df4ff",
            "on-surface-variant": "#e4bdbf",
            "primary": "#ffb2b8",
            "tertiary-fixed-dim": "#00dbe9",
            "outline": "#ab888a",
            "graphite-base": "#0d0d0e",
            "surface-container": "#1e2022",
            "error-container": "#93000a",
            "pure-white": "#ffffff",
            "surface-container-lowest": "#0d0e11",
            "on-primary": "#67001d",
            "surface-variant": "#343538",
            "inverse-on-surface": "#2f3033",
            "tertiary-container": "#00848d",
            "holographic-blue": "#00f0ff"
        },
        borderRadius: {
            "DEFAULT": "0.125rem",
            "lg": "0.25rem",
            "xl": "0.5rem",
            "full": "0.75rem"
        },
        spacing: {
            "md": "24px",
            "gutter": "24px",
            "sm": "16px",
            "lg": "48px",
            "margin-desktop": "64px",
            "margin-mobile": "16px",
            "xs": "8px",
            "section-gap": "112px",
            "xl": "80px",
            "base": "4px"
        },
        fontFamily: {
            "display-hero": ["anton"],
            "label-caps": ["inter"],
            "body-md": ["inter"],
            "headline-md": ["inter"],
            "headline-lg": ["anton"],
            "body-lg": ["inter"],
            "display-hero-mobile": ["anton"]
        },
        fontSize: {
            "display-hero": ["80px", { "lineHeight": "0.9", "letterSpacing": "-0.04em", "fontWeight": "400" }],
            "label-caps": ["12px", { "lineHeight": "1.0", "letterSpacing": "0.1em", "fontWeight": "700" }],
            "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
            "headline-md": ["32px", { "lineHeight": "1.3", "fontWeight": "600" }],
            "headline-lg": ["48px", { "lineHeight": "1.1", "fontWeight": "400" }],
            "body-lg": ["20px", { "lineHeight": "1.5", "fontWeight": "400" }],
            "display-hero-mobile": ["48px", { "lineHeight": "1.0", "letterSpacing": "-0.02em", "fontWeight": "400" }]
        }
    },
  },
  plugins: [
    require('@tailwindcss/forms'),
    require('@tailwindcss/container-queries'),
  ],
}
